apiVersion: v1
kind: Secret
metadata:
  name: xapisecrets
type: Opaque
stringData: 
  APIBaseUrl: $XRapidAPIBaseUrl
  APIHost: $XRapidAPIHost
  APIKey: $XRapidAPIKey

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-geocities-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eg-geocities-management
  template:
    metadata:
      labels:
        app: eg-geocities-management
    spec:
      containers:
      - image: inftfg2021/eg.geocities.management:$TAG
        name: eg-geocities-management
        env: 
          - name: NODE_ENV
            value: $ENV
          - name: APIBaseUrl
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: APIBaseUrl
          - name: APIHost
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: APIHost
          - name: APIKey
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: APIKey
---
apiVersion: v1
kind: Service
metadata:
  name: eg-geocities-management
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "eg-geocities-management"
    port: 3000
  selector:
    app: eg-geocities-management
