apiVersion: v1
kind: Secret
metadata:
  name: RapidAPISecrets
type: Opaque
stringData: 
  config.yml: |
    XRapidAPIBaseUrl: $XRapidAPIBaseUrl
    XRapidAPIHost: $XRapidAPIHost
    XRapidAPIKey: $XRapidAPIKey

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-geocities-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eg-geocities-management
  template:
    metadata:
      labels:
        app: eg-geocities-management
    spec:
      containers:
      - image: inftfg2021/eg.identity.management:latest
        name: eg-geocities-management
        env: 
          - name: NODE_ENV
            value: Development
          - name: XRapidAPIBaseUrl
            valueFrom:
              secretKeyRef:
                name: RapidAPISecrets
                key: XRapidAPIBaseUrl
          - name: XRapidAPIHost
            valueFrom:
              secretKeyRef:
                name: RapidAPISecrets
                key: XRapidAPIHost
           - name: XRapidAPIKey
            valueFrom:
              secretKeyRef:
                name: RapidAPISecrets
                key: XRapidAPIKey
---
apiVersion: v1
kind: Service
metadata:
  name: eg-geocities-management
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "eg-geocities-management"
    port: 3000
  selector:
    app: eg-geocities-management
