name: Build and Deploy in DEV Namespace

on: 
 push:
  branches:
    - feature/including_semantic_versioning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Applications Within the Repository.
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build

    - name: Application Versioning
      id: appVersioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "dev-"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        namespace: ''
        bump_each_commit: true
        search_commit_body: true
        user_format_type: "csv"
    
    - name: Verifying Docker Credentials
      uses: actions-hub/docker/login@master 
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}   

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/eg-geocities-management:${{ steps.appVersioning.outputs.version_tag }} -f ./apps/geography/Dockerfile .

    - name: Publish Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker push ${{ secrets.DOCKER_USER }}/eg-geocities-management:${{ steps.appVersioning.outputs.version_tag }}   